---

################################################################
## load the needed vars
################################################################

- name: Load vars
  hosts: "*"
  tasks:
    - name: Include vars
      include_vars:
        file: "./vars/$(stackid)_common.yaml"
    - name: Include vars
      include_vars:
        file: "{{ ansible_env.HOME }}/.ansible_vars/$(stackid)_deployer_secrets.yaml"
  tags:
    - always

################################################################
## Integration server runtime
################################################################

- import_playbook: sagenv-common-webmethods.yaml
  vars:
    cce_provisioning_inventory_hosts_pattern: $(stackid)deployer
    cce_provisioning_template: integrationserver/template-runtime-dsl1.1.yaml
    cce_provisioning_properties: integrationserver-runtime-dsl1.1
    cce_provisioning_template_params:
      - name: "repo.product"
        value: "{{ cce_provisioning_products_repo_is }}"
      - name: "repo.fix"
        value: "{{ cce_provisioning_fixes_repo_is }}"
      - name: "products.fixes"
        value: "{{ cce_provisioning_fixes_apply_isruntime }}"
      - name: "is.memory.init"
        value: "1024"
      - name: "is.memory.max"
        value: "4096"
      - name: "is.instance.name"
        value: "{{ webmethods_deployer_is_instance_name }}"
      - name: "is.key.license.alias"
        value: "*_PIE_10.*_*_*"
    cce_provisioning_template_params_secure:
      - name: "administrator.password"
        value: "{{ is_administrator_password }}"
  tags:
    - install
    - install-runtime

- import_playbook: sagenv-common-webmethods-postinstall.yaml
  vars:
    cce_provisioning_inventory_hosts_pattern: $(stackid)deployer
    cce_provisioning_installed_product_names: integrationserver
    cce_provisioning_installed_product_instance_names: "{{ webmethods_deployer_is_instance_name }}"
    cce_provisioning_validation_ports:
      - 5555
  tags:
    - install
    - install-runtime
    - install-runtime-postinstall

################################################################
## Integration server components
################################################################

- import_playbook: sagenv-common-webmethods.yaml
  vars:
    cce_provisioning_inventory_hosts_pattern: $(stackid)deployer
    cce_provisioning_template: integrationserver/components/template-deployer.yaml
    cce_provisioning_properties: integrationserver-components-common
    cce_provisioning_template_params:
      - name: "repo.product"
        value: "{{ cce_provisioning_products_repo_deployer }}"
      - name: "repo.fix"
        value: "{{ cce_provisioning_fixes_repo_deployer }}"
      - name: "products.fixes"
        value: "{{ cce_provisioning_fixes_apply_deployer }}"
      - name: "is.instance.name"
        value: "{{ webmethods_deployer_is_instance_name }}"
  tags:
    - install
    - install-integrationserver-components
    - install-integrationserver-deployer

###############################################################
# Integration server configs
###############################################################


################################################################
## final restart
################################################################

- import_playbook: sagenv-common-webmethods-postinstall.yaml
  vars:
    cce_provisioning_inventory_hosts_pattern: $(stackid)deployer
    cce_provisioning_postinstall_webmethods: false
    cce_provisioning_postinstall_service_setup: false
    cce_provisioning_postinstall_reboot: true
    cce_provisioning_validation_ports:
      - 5555
  tags:
    - install
    - install-final