---

- hosts: localhost
  vars_prompt:
    - name: "db_password"
      prompt: "Enter the password for DB username"
      private: yes
    - name: "administrator_password"
      prompt: "Enter the password for default Administrator user"
      private: yes

  tasks:
    # - name: Encrypt variable file
    #   shell: ansible-vault encrypt vars/$(stackid)_iscore_secrets.yaml
    
    - name: Write params to file
      blockinfile:
        path: "{{ ansible_env.HOME }}/.ansible_vars/$(stackid)_iscore_secrets.yaml"
        create: yes
        backup: yes
        mode: 0600
        block: |
          is_db_password: "{{ db_password }}"
          is_administrator_password: "{{ administrator_password }}"