
## needed to use the service role
product_version_major: 10
product_version_minor: 5
product_version_full: "{{ product_version_major }}{{ product_version_minor }}"

cce_provisioning_inventory_hosts_property: fqdn
cce_provisioning_inventory_aliases_property: ""
cce_provisioning_inventory_aliasmapping_delimiter: "_"
cce_provisioning_inventory_aliasmapping_prefix: "{{ cce_provisioning_inventory_hosts_pattern }}"

###########################################################
################ Products / Fixes Repositories to use
###########################################################

cce_provisioning_products_repo_sdc: "webMethods-{{ product_version_major }}.{{ product_version_minor }}"
cce_provisioning_fixes_repo_sdc: "Empower"

cce_provisioning_products_repo_apigateway: "softwareag_105_apigateway_linux_x64"
cce_provisioning_fixes_repo_apigateway: "{{ cce_provisioning_fixes_repo_sdc }}"
cce_provisioning_products_repo_internaldatastore: "softwareag_105_apigateway_linux_x64"
cce_provisioning_fixes_repo_internaldatastore: "{{ cce_provisioning_fixes_repo_sdc }}"
cce_provisioning_products_repo_terracotta: "softwareag_bigmemorymax43_linux_x64"
cce_provisioning_fixes_repo_terracotta: "{{ cce_provisioning_fixes_repo_sdc }}"
cce_provisioning_products_repo_apiportal: "softwareag_105_apiportal_linux_x64"
cce_provisioning_fixes_repo_apiportal: "{{ cce_provisioning_fixes_repo_sdc }}"

##################################################
################ Fixes to apply
##################################################

cce_provisioning_fixes_apply_apigateway: "ALL"
cce_provisioning_fixes_apply_internaldatastore: "ALL"
cce_provisioning_fixes_apply_terracotta: "ALL"
cce_provisioning_fixes_apply_apiportal: "ALL"

##################################################
################ App details
##################################################

## important: this is used by the installer to find the files
cce_provisioning_content_localpath: /opt/softwareag/webmethods-devops-sagcontent/

## API portal ACC details
webmethods_apiportal_acc_host: localhost
webmethods_apiportal_acc_port: 18011
webmethods_apiportal_acc_user: Clous
webmethods_apiportal_acc_password: "{{ apiportal_cloudagent_password }}"
webmethods_apiportal_acc_install_size: medium
webmethods_apiportal_loadbalancer_fqdn: "apiportal-$(stackenv).clouddemo.saggov.com"