---

################################################################
## Load stack variables
################################################################

- name: Load vars
  hosts: "*"
  tasks:
    - name: Include vars
      include_vars:
        file: "./vars/$(stackid)_common.yaml"
    - name: Include vars
      include_vars:
        file: "{{ ansible_env.HOME }}/.ansible_vars/$(stackid)_apiportal_secrets.yaml"
  tags:
    - always
    
################################################################
## API Portal post install tasks
################################################################

- hosts: $(stackid)apiportal
  become: true
  become_user: "{{ webmethods_user }}"
  tasks:
    - import_role: 
        name: command-apiportal
      vars:
        webmethods_apiportal_acc_command: "startall"