---

################################################################
## Load stack variables
################################################################

- name: Load vars
  hosts: "*"
  tasks:
    - name: Include vars
      include_vars:
        file: "./vars/$(stackid)_common.yaml"
  tags:
    - always

################################################################
## internal data store provisioning
################################################################

- import_playbook: sagenv-common-webmethods.yaml
  vars:
    cce_provisioning_inventory_hosts_pattern: $(stackid)internaldatastore
    cce_provisioning_template: internaldatastore/template-cluster-dsl1.1.yaml
    cce_provisioning_properties: internaldatastore
    cce_provisioning_template_params:
      - name: "repo.product"
        value: "{{ cce_provisioning_products_repo_internaldatastore }}"
      - name: "repo.fix"
        value: "{{ cce_provisioning_fixes_repo_internaldatastore }}"
      - name: "products.fixes"
        value: "{{ cce_provisioning_fixes_apply_internaldatastore }}"
  tags:
    - install
    - install-runtime

- import_playbook: sagenv-common-webmethods-postinstall.yaml
  vars:
    cce_provisioning_inventory_hosts_pattern: $(stackid)internaldatastore
    cce_provisioning_installed_product_names: internaldatastore
    cce_provisioning_postinstall_webmethods: true
    cce_provisioning_postinstall_service_setup: true
    cce_provisioning_postinstall_reboot: false
    cce_provisioning_validation_ports:
      - 9240
      - 9340
  tags:
    - install
    - install-runtime
    - install-runtime-postinstall

################################################################
## internal data store post install cluster tweaking
################################################################

- hosts: $(stackid)internaldatastore
  become: true
  tasks:
    - import_role: 
        name: service-webmethods
      vars:
        product_command: "stop"
        product_name: "internaldatastore"
    - import_role: 
        name: elasticsearch-update-seeds
      vars:
        inventory_pattern: $(stackid)internaldatastore
        inventory_hosts_property: fqdn
      become_user: "{{ webmethods_user }}"
    ##TODO: we should be careful not to run this when product is already in use...otherwise would lose all the data
    - import_role: 
        name: elasticsearch-cleardata
      become_user: "{{ webmethods_user }}"    
    - import_role: 
        name: service-webmethods
      vars:
        product_command: "start"
        product_name: "internaldatastore"  
  tags:
    - install
    - install-configs

################################################################
## final restart
################################################################

- import_playbook: sagenv-common-webmethods-postinstall.yaml
  vars:
    cce_provisioning_inventory_hosts_pattern: $(stackid)internaldatastore
    cce_provisioning_postinstall_webmethods: false
    cce_provisioning_postinstall_service_setup: false
    cce_provisioning_postinstall_reboot: true
    cce_provisioning_validation_ports:
      - 9240
      - 9340
  tags:
    - install
    - install-final