---

- hosts: localhost
  vars_prompt:
    - name: "cloud_agent_password"
      prompt: "Enter the password for API Portal cloud agent user"
      private: yes

  tasks:
    # - name: Encrypt variable file
    #   shell: ansible-vault encrypt vars/$(stackid)_iscore_secrets.yaml
    
    - name: Write params to file
      blockinfile:
        path: "{{ ansible_env.HOME }}/.ansible_vars/$(stackid)_apiportal_secrets.yaml"
        create: yes
        backup: yes
        mode: 0600
        block: |
          apiportal_cloudagent_password: "{{ cloud_agent_password }}"