---

################################################################
## Load stack variables
################################################################

- name: Load vars
  hosts: "*"
  tasks:
    - name: Include vars
      include_vars:
        file: "./vars/$(stackid)_common.yaml"
  tags:
    - always

################################################################
## SPM bootstrapping full stack
################################################################

- import_playbook: sagenv-common-spm-bootstrap-aliasmapping.yaml
  vars:
    cce_provisioning_inventory_hosts_pattern: $(stackid)apigateway

- import_playbook: sagenv-common-spm-bootstrap-aliasmapping.yaml
  vars:
    cce_provisioning_inventory_hosts_pattern: $(stackid)internaldatastore

- import_playbook: sagenv-common-spm-bootstrap-aliasmapping.yaml
  vars:
    cce_provisioning_inventory_hosts_pattern: $(stackid)apiportal