---

################################################################
## load the needed vars
################################################################

- name: Load vars
  hosts: "*"
  tasks:
    - name: Include vars
      include_vars:
        file: "./vars/$(stackid)_common.yaml"
    - name: Include vars
      include_vars:
        file: "{{ ansible_env.HOME }}/.ansible_vars/$(stackid)_jenkins_secrets.yaml"
  tags:
    - always

################################################################
## Integration server runtime
################################################################

- hosts: $(stackid)jenkins
  become: true

  vars:
    jenkins_version: "2.238"
    jenkins_prefer_lts: false
    jenkins_hostname: "{{ jenkins_hostname_fqdn }}"
    jenkins_java_options: "{{ jenkins_java_options }}"
    jenkins_home: /var/lib/jenkins
    jenkins_admin_username: "{{ jenkins_administrator_username }}"
    jenkins_admin_password: "{{ jenkins_administrator_password }}"
    jenkins_plugins:
      - blueocean
    jenkins_plugins_install_dependencies: true
    jenkins_plugins_state: latest
    jenkins_plugin_timeout: 30
    java_packages:
      - java-1.8.0-openjdk
    jenkins_url: "https://mgt-jenkins.clouddemo.saggov.com"
    jenkins_admin: "admin@softwareaggov.com"
    jenkins_process_user: jenkins
    jenkins_process_group: "{{ jenkins_process_user }}"

  roles:
    - role: jenkins