---

################################################################
## Load stack variables
################################################################

- name: Load vars
  hosts: "*"
  tasks:
    - name: Include vars
      include_vars:
        file: "./vars/$(stackid)_common.yaml"
  tags:
    - always

################################################################
## SPM command task
################################################################

- import_playbook: sagenv-tools-command-spm.yaml
  vars:
    inventory_groupnames: $(stackid)tnserver
    checkport_inventory_hosts_property: fqdn
  tags:
    - tnserver-spm

################################################################
## IS command task
################################################################

- import_playbook: sagenv-tools-command-integrationserver.yaml
  vars:
    inventory_groupnames: $(stackid)tnserver
    product_instance_name: default
    checkport_inventory_hosts_property: fqdn
  tags:
    - tnserver-runtime