---
- hosts: localhost

  vars_prompt:
    - name: "dbserver_root_password"
      prompt: "Enter the DB root user password"
      private: yes

  tasks:
    - name: Write params to file
      blockinfile:
        path: "{{ ansible_env.HOME }}/.ansible_vars/$(stackid)_dbserver_secrets.yaml"
        create: yes
        backup: yes
        mode: 0600
        block: |
          dbserver_root_password: "{{ dbserver_root_password }}"